logging:
  config: classpath:log4j2-default.xml
  
spring:
  profiles: 
    active: inhouse
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//192.168.0.67:1524/UTILITY
    username: DPW_DTCR
    password: jT3$2dP$41
    platform: oracle
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        dialect: org.hibernate.dialect.Oracle10gDialect
        default-schema: DPW_DTCR
    hibernate:
        ddl-auto: none              
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true  
wms:
  fileupload:
    basepath: F://dpcrUpload
    maxsize:  10000000  # = 10MB max fIle size
  defaults:
    currency: AED
    
dpwms:
  api:
    username: DPW_WMS_TM_DEV
    password: TM#wms@1
    url:
      hs_code: https://otmdev-oic-dpwglobalpass.integration.ocp.oraclecloud.com/ic/api/integration/v1/flows/rest/DPW_INT_TM_ITEMS_DTLS/1.0/getData
      sequence: https://otmdev-oic-dpwglobalpass.integration.ocp.oraclecloud.com/ic/api/integration/v1/flows/rest/DPW_INT_TM_GET_SEQ_IB_OB/1.0/getSequence?name=
      push_inbound: https://OTMDEV-OIC-dpwglobalpass.integration.ocp.oraclecloud.com/ic/api/integration/v1/flows/rest/DPW_INT_WMS_TM_INBOU_TXN/1.0/create/inventory
      push_return_goods: https://OTMDEV-OIC-dpwglobalpass.integration.ocp.oraclecloud.com/ic/api/integration/v1/flows/rest/DPW_INT_WMS_TM_GOOD_TXN/1.0/returngoods/inventory
      push_return_local_goods: https://OTMDEV-OIC-dpwglobalpass.integration.ocp.oraclecloud.com/ic/api/integration/v1/flows/rest/DPW_INT_WMS_TM_RETU_LOCA_GOOD_TX/1.0/returnlocalgoods/inventory
      push_outbound: https://OTMDEV-OIC-dpwglobalpass.integration.ocp.oraclecloud.com/ic/api/integration/v1/flows/rest/DPW_INT_WMS_TM_OUTBO_TXN/1.0/outbound/inventory
      push_barcode: https://OTMDEV-OIC-dpwglobalpass.integration.ocp.oraclecloud.com/ic/api/integration/v1/flows/rest/DPW_INT_TM_ITEMS_DTLS/1.0/pushitems 
inventory:
  restrict:
    update: 30
    
scheduler:
    fetchCRMdataInMills: 120000
    fetchCRMdataEnabled: true
    pushCRMdataInMills: 120000
    pushCRMdataEnabled: true
    sendSurveyInMills : 120000
    sendSurveyEnabled : true
   