logging:
  config: classpath:log4j2-uat.xml
  
cors:
  allowed-origins: https://ymsuat.dpworld.com

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//192.168.0.67:1524/UTILITY
    username: DPW_DTCR
    password: jT3$2dP$41
    platform: oracle
    tomcat:
      initial-size: 15
      max-wait: 30000
      max-active: 100
      max-idle: 15
      min-idle: 10
      default-auto-commit: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        dialect: org.hibernate.dialect.Oracle10gDialect
        default-schema: DPW_DTCR
    hibernate:
        ddl-auto: none
        
wms:
  fileupload:
    basepath: /u01/apps/TST/TMWmsUpload
    maxsize: 20000000  # = 20MB max fIle size
  defaults:
    currency: AED
    
dubaitrade:
  api:
    username: dpwtm
    password: Login345
    acceess_key: 05a5489b5753a2be7be71bf00f216823ccdaa515
    url:
      validate_user_service: https://eservicesuat.dubaitrade.ae/umwsrest/api/company/v1/validateUserService
      fetch_company_info: https://eservicesuat.dubaitrade.ae/umwsrest/api/company/v1/fetchUserCompanyInfo
  validate:
    serviceId: 25794088
    agent-type-code: I
    
dpwms:
  api:
    username: DPW_WMS_JA_UAT
    password: Uatoic*123
    url:
      hs_code: https://otmuat-oic-dpwglobalpass-fr.integration.ocp.oraclecloud.com/ic/api/integration/v1/flows/rest/DPW_INT_TM_ITEMS_DTLS/1.0/getData
      sequence: https://otmuat-oic-dpwglobalpass-fr.integration.ocp.oraclecloud.com/ic/api/integration/v1/flows/rest/DPW_INT_TM_GET_SEQ_IB_OB/1.0/getSequence?name=
      push_inbound: https://otmuat-oic-dpwglobalpass-fr.integration.ocp.oraclecloud.com/ic/api/integration/v1/flows/rest/DPW_INT_WMS_TM_INBOU_TXN/1.0/create/inventory
      push_return_goods: https://otmuat-oic-dpwglobalpass-fr.integration.ocp.oraclecloud.com/ic/api/integration/v1/flows/rest/DPW_INT_WMS_TM_GOOD_TXN/1.0/returngoods/inventory
      push_return_local_goods: https://otmuat-oic-dpwglobalpass-fr.integration.ocp.oraclecloud.com/ic/api/integration/v1/flows/rest/DPW_INT_WMS_TM_RETU_LOCA_GOOD_TX/1.0/returnlocalgoods/inventory
      push_outbound: https://otmuat-oic-dpwglobalpass-fr.integration.ocp.oraclecloud.com/ic/api/integration/v1/flows/rest/DPW_INT_WMS_TM_OUTBO_TXN/1.0/outbound/inventory
      push_barcode: https://otmuat-oic-dpwglobalpass-fr.integration.ocp.oraclecloud.com/ic/api/integration/v1/flows/rest/DPW_INT_TM_ITEMS_DTLS/1.0/pushitems